// Explicitly blocked user IDs (normalized to lowercase for validation).
export const FORBIDDEN_USER_IDS = [
    "admin",
    "administrator",
    "root",
    "system",
    "sys",
    "operator",
    "owner",
    "staff",
    "support",
    "help",
    "official",
    "info",
    "contact",
    "service",
    "services",
    "server",
    "host",
    "master",
    "moderator",
    "mod",
    "security",
    "trust",
    "verify",
    "verified",
    "bot",
    "api",
    "backend",
    "frontend",
    "client",
    "console",
    "panel",
    "dashboard",
    "control",
    "manage",
    "management",
    "manager",
    "setting",
    "settings",
    "config",
    "configuration",
    "account",
    "accounts",
    "profile",
    "profiles",
    "user",
    "users",
    "member",
    "members",
    "guest",
    "anonymous",
    "me",
    "self",
    "you",
    "everyone",
    "all",
    "public",
    "private",
    "home",
    "index",
    "top",
    "main",
    "start",
    "login",
    "logout",
    "signin",
    "signup",
    "register",
    "auth",
    "oauth",
    "callback",
    "redirect",
    "session",
    "token",
    "password",
    "reset",
    "forgot",
    "search",
    "explore",
    "discover",
    "timeline",
    "feed",
    "post",
    "posts",
    "comment",
    "comments",
    "reply",
    "replies",
    "message",
    "messages",
    "dm",
    "inbox",
    "outbox",
    "notification",
    "notifications",
    "alert",
    "alerts",
    "news",
    "announce",
    "announcement",
    "update",
    "updates",
    "release",
    "releases",
    "event",
    "events",
    "campaign",
    "promo",
    "promotion",
    "ads",
    "advertisement",
    "marketing",
    "status",
    "health",
    "monitor",
    "log",
    "logs",
    "history",
    "activity",
    "analytics",
    "report",
    "reports",
    "stat",
    "stats",
    "data",
    "database",
    "db",
    "backup",
    "restore",
    "import",
    "export",
    "upload",
    "download",
    "file",
    "files",
    "image",
    "images",
    "video",
    "videos",
    "media",
    "static",
    "assets",
    "cdn",
    "cache",
    "tmp",
    "temp",
    "test",
    "testing",
    "sample",
    "example",
    "demo",
    "debug",
    "dev",
    "development",
    "staging",
    "stage",
    "prod",
    "production",
    "build",
    "deploy",
    "deployment",
    "ci",
    "cd",
    "cron",
    "job",
    "jobs",
    "queue",
    "worker",
    "workers",
    "null",
    "nil",
    "none",
    "undefined",
    "void",
    "true",
    "false",
    "nan",
    "zero",
    "one",
    "system32",
    "windows",
    "linux",
    "mac",
    "android",
    "ios",
    "google",
    "apple",
    "amazon",
    "meta",
    "facebook",
    "instagram",
    "twitter",
    "x",
    "youtube",
    "tiktok",
    "line",
    "discord",
    "github",
    "openai",
    "chatgpt",
    "microsoft",
    "japan",
    "tokyo",
    "osaka",
    "government",
    "gov",
    "prime_minister",
    "ministry",
    "police",
    "fire",
    "firefighter",
    "city",
    "cityhall",
    "prefecture",
    "school",
    "university",
    "hospital",
    "bank",
    "finance",
    "money",
    "payment",
    "billing",
    "invoice",
    "order",
    "orders",
    "shop",
    "store",
    "market",
    "fuck",
    "shit",
    "sex",
    "porn",
    "xxx",
    "nude",
    "nsfw",
    "hate",
    "kill",
    "die",
    "murder",
    "terror",
    "nazi",
    "drug",
    "weapon",
    "gun",
    "bomb",
];

// Wildcard-like patterns to reject (use with startsWith/endsWith checks).
export const FORBIDDEN_USER_ID_PATTERNS = [
    "admin*",
    "*_admin",
    "support*",
    "official*",
    "mod*",
    "sys*",
    "test*",
    "dev*",
];
/**
 * Validates if a user ID is allowed.
 * @param userIdentifier - The user ID to validate (case-insensitive)
 * @returns { valid: boolean, reason?: string }
 */
export function validateUserIdentifier(userIdentifier: string): {
  valid: boolean;
  reason?: string;
} {
  if (!userIdentifier || userIdentifier.trim().length === 0) {
    return { valid: false, reason: "ユーザーIDは空にできません" };
  }

  const normalized = userIdentifier.toLowerCase().trim();

  // Check against forbidden list
  if (FORBIDDEN_USER_IDS.includes(normalized)) {
    return {
      valid: false,
      reason: "このユーザーIDは設定できません",
    };
  }

  // Check against wildcard patterns
  for (const pattern of FORBIDDEN_USER_ID_PATTERNS) {
    if (pattern.startsWith("*") && pattern.endsWith("*")) {
      // *pattern* - contains
      const middle = pattern.slice(1, -1);
      if (normalized.includes(middle)) {
        return {
          valid: false,
          reason: "このユーザーIDは設定できません",
        };
      }
    } else if (pattern.startsWith("*")) {
      // *pattern - ends with
      const suffix = pattern.slice(1);
      if (normalized.endsWith(suffix)) {
        return {
          valid: false,
          reason: "このユーザーIDは設定できません",
        };
      }
    } else if (pattern.endsWith("*")) {
      // pattern* - starts with
      const prefix = pattern.slice(0, -1);
      if (normalized.startsWith(prefix)) {
        return {
          valid: false,
          reason: "このユーザーIDは設定できません",
        };
      }
    }
  }

  return { valid: true };
}